apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: examiq-kv-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "4864160d-3882-4bf4-8300-d1bd6e88573d"
    keyvaultName: "examiq-kv"
    tenantId: "41bc598c-c580-4b0d-97eb-1b82954bdbb5"
    objects: |
      array:
        - |
          objectName: GEMINI-API-KEY
          objectType: secret
        - |
          objectName: COSMOS-DB-CONNECTION-STRING
          objectType: secret
        - |
          objectName: USE-SQLITE
          objectType: secret